security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    encoders:
        App\Entity\User:
            algorithm: plaintext

    providers:
        our_db-provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        register:
            pattern: ^/api/register
            stateless: true
            anonymous: true

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        sector:
            pattern: ^/api/sectors
            stateless: true
            anonymous: true

        position:
            pattern: ^/api/positions
            stateless: true
            anonymous: true

        race:
            pattern: ^/api/races
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/sectors, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/positions, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/races, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
