#index:
#    path: /
#    controller: App\Controller\DefaultController::index
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
api_login_check:
    path: /api/login_check
